# Generated by Django 3.0.5 on 2020-05-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
